#!/usr/bin/env bash
# Trust manifest — .trust file generation and validation for owned skills
# A .trust file pins a verified skill's content hash so it can skip quarantine

TRUST_MANIFEST_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
if [[ -z "${SCAN_PATTERNS+x}" ]]; then
  source "$TRUST_MANIFEST_DIR/patterns.sh"
fi

# Compute SHA-256 hash of all skill files (excluding .trust and .scanignore)
# Usage: compute_skill_hash <skill_dir>
compute_skill_hash() {
  local skill_dir="$1"
  local hash
  hash=$(find "$skill_dir" -maxdepth 2 -type f \
    ! -name '.trust' ! -name '.scanignore' \
    | sort | xargs cat 2>/dev/null | sha256sum | cut -d' ' -f1)
  echo "sha256:$hash"
}

# Generate a .trust manifest for a verified skill
# Usage: generate_trust_manifest <skill_dir> [total_lines] [safe_lines] [suspicious_lines]
generate_trust_manifest() {
  local skill_dir="$1"
  local total_lines="${2:-0}"
  local safe_lines="${3:-0}"
  local suspicious_lines="${4:-0}"
  local trust_file="$skill_dir/.trust"

  local hash
  hash=$(compute_skill_hash "$skill_dir")
  local timestamp
  timestamp=$(date -u +%Y-%m-%dT%H:%M:%SZ 2>/dev/null || date +%Y-%m-%dT%H:%M:%SZ)
  local pattern_count=${#SCAN_PATTERNS[@]}

  cat > "$trust_file" <<EOF
# Auto-generated by skill-verify.sh — do not edit manually
VERIFIED_AT=$timestamp
VERIFIED_BY=openagent-skills-pipeline
VERIFY_HASH=$hash
LINES_TOTAL=$total_lines
LINES_SAFE=$safe_lines
LINES_SUSPICIOUS=$suspicious_lines
SCAN_PATTERNS=$pattern_count
VERIFY_VERSION=1.0.0
EOF
}

# Validate a .trust file against current skill content
# Returns 0 if valid (hash matches), 1 if invalid
# Usage: validate_trust_manifest <skill_dir>
validate_trust_manifest() {
  local skill_dir="$1"
  local trust_file="$skill_dir/.trust"

  [[ -f "$trust_file" ]] || return 1

  local stored_hash
  stored_hash=$(grep '^VERIFY_HASH=' "$trust_file" 2>/dev/null | cut -d= -f2)
  [[ -n "$stored_hash" ]] || return 1

  local current_hash
  current_hash=$(compute_skill_hash "$skill_dir")

  [[ "$stored_hash" == "$current_hash" ]]
}
